##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Thu Mar 8 17:25:49 2018
##END:date
##START:preamble
ROOTDIR := /home/finnerty/src/ionch/BOUML/PNP
OUTPUTDIR := /home/finnerty/src/ionch/BOUML/PNP
include $(ROOTDIR)/M_sys.mk

CPPFLAGS+=-I$(ROOTDIR)/src 
CCFLAGS+=-std=c++11 
CCCFLAGS+=-std=c++11 
##END:preamble
##START:target utility
dirs += src/utility
##END:target utility
##START:target core
dirs += src/core
##END:target core
##START:target core_test
dirs += src/core/core_test
##END:target core_test
##START:target particle
dirs += src/particle
##END:target particle
##START:target particle_test
dirs += src/particle/particle_test
##END:target particle_test
##START:target platform
dirs += src/platform
##END:target platform
##START:target platform_test
dirs += src/platform/platform_test
##END:target platform_test
##START:target cscpbc
dirs += src/cscpbc
##END:target cscpbc
##START:target cscchannel
dirs += src/cscchannel
##END:target cscchannel
##START:target trial
dirs += src/trial
##END:target trial
##START:target trial_test
dirs += src/trial/trial_test
##END:target trial_test
##START:target evaluator
dirs += src/evaluator
##END:target evaluator
##START:target evaluator_test
dirs += src/evaluator/evaluator_test
##END:target evaluator_test
##START:target observable
dirs += src/observable
##END:target observable
##START:target geometry
dirs += src/geometry
##END:target geometry
##START:target geometry_test
dirs += src/geometry/geometry_test
##END:target geometry_test
##START:target observable_test
dirs += src/observable/observable_test
##END:target observable_test
##START:target utility_test
dirs += src/utility/utility_test
##END:target utility_test
